### ISSUE TITLE
Can i install PHP Extension bcmath?

### ISSUE THREAD

**Issue by Kuroiras** [Ym0T/pterodactyl-nginx-egg#1]
im just trying to install azuriom but i need this extension to continue, the image has a ReadonlyRootfs:true so i cant install it can you help me?
![image](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/92393258/d9833744-2175-4aeb-bb08-acac1e6bf24a)

**Comment by Ym0T** [comment]
Hello, I'm updating the Docker images of the different PHP versions tonight and adding Bcmath.

**Comment by Kuroiras** [comment]
Tanks!!! really you save me

**Comment by Ym0T** [comment]
Bcmath was added. Restart the web server once and bcmath will be installed automatically.

**Comment by Kuroiras** [comment]
now i got this 
![image](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/92393258/9eab5c0f-95c6-4392-af87-44aa008bd29e)

**Comment by Kuroiras** [comment]
I'm not very sure but I think that in the change only the extensions are being installed but not the complete PHP package that already installs other extensions by default as you did previously
![image](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/92393258/58ec8184-3914-47f0-aad1-e332bb347b0d)

**Comment by Ym0T** [comment]
But all common extensions will be downloaded. See PHP Info. I have now added the desired extensions as well. Test it out once.

`/etc/php/8.3/fpm/conf.d/10-mysqlnd.ini, /etc/php/8.3/fpm/conf.d/10-opcache.ini, /etc/php/8.3/fpm/conf.d/10-pdo.ini, /etc/php/8.3/fpm/conf.d/15-psr.ini, /etc/php/8.3/fpm/conf.d/15-xml.ini, /etc/php/8.3/fpm/conf.d/20-calendar.ini, /etc/php/8.3/fpm/conf.d/20-ctype.ini, /etc/php/8.3/fpm/conf.d/20-curl.ini, /etc/php/8.3/fpm/conf.d/20-dba.ini, /etc/php/8.3/fpm/conf.d/20-dom.ini, /etc/php/8.3/fpm/conf.d/20-exif.ini, /etc/php/8.3/fpm/conf.d/20-ffi.ini, /etc/php/8.3/fpm/conf.d/20-fileinfo.ini, /etc/php/8.3/fpm/conf.d/20-ftp.ini, /etc/php/8.3/fpm/conf.d/20-gettext.ini, /etc/php/8.3/fpm/conf.d/20-iconv.ini, /etc/php/8.3/fpm/conf.d/20-igbinary.ini, /etc/php/8.3/fpm/conf.d/20-imagick.ini, /etc/php/8.3/fpm/conf.d/20-imap.ini, /etc/php/8.3/fpm/conf.d/20-intl.ini, /etc/php/8.3/fpm/conf.d/20-ldap.ini, /etc/php/8.3/fpm/conf.d/20-mbstring.ini, /etc/php/8.3/fpm/conf.d/20-memcache.ini, /etc/php/8.3/fpm/conf.d/20-mongodb.ini, /etc/php/8.3/fpm/conf.d/20-msgpack.ini, /etc/php/8.3/fpm/conf.d/20-mysqli.ini, /etc/php/8.3/fpm/conf.d/20-oauth.ini, /etc/php/8.3/fpm/conf.d/20-odbc.ini, /etc/php/8.3/fpm/conf.d/20-pcov.ini, /etc/php/8.3/fpm/conf.d/20-pdo_dblib.ini, /etc/php/8.3/fpm/conf.d/20-pdo_firebird.ini, /etc/php/8.3/fpm/conf.d/20-pdo_mysql.ini, /etc/php/8.3/fpm/conf.d/20-pdo_odbc.ini, /etc/php/8.3/fpm/conf.d/20-pdo_pgsql.ini, /etc/php/8.3/fpm/conf.d/20-pdo_sqlite.ini, /etc/php/8.3/fpm/conf.d/20-pgsql.ini, /etc/php/8.3/fpm/conf.d/20-phar.ini, /etc/php/8.3/fpm/conf.d/20-posix.ini, /etc/php/8.3/fpm/conf.d/20-ps.ini, /etc/php/8.3/fpm/conf.d/20-pspell.ini, /etc/php/8.3/fpm/conf.d/20-readline.ini, /etc/php/8.3/fpm/conf.d/20-shmop.ini, /etc/php/8.3/fpm/conf.d/20-simplexml.ini, /etc/php/8.3/fpm/conf.d/20-smbclient.ini, /etc/php/8.3/fpm/conf.d/20-snmp.ini, /etc/php/8.3/fpm/conf.d/20-soap.ini, /etc/php/8.3/fpm/conf.d/20-sockets.ini, /etc/php/8.3/fpm/conf.d/20-solr.ini, /etc/php/8.3/fpm/conf.d/20-sqlite3.ini, /etc/php/8.3/fpm/conf.d/20-ssh2.ini, /etc/php/8.3/fpm/conf.d/20-stomp.ini, /etc/php/8.3/fpm/conf.d/20-sysvmsg.ini, /etc/php/8.3/fpm/conf.d/20-sysvsem.ini, /etc/php/8.3/fpm/conf.d/20-sysvshm.ini, /etc/php/8.3/fpm/conf.d/20-tokenizer.ini, /etc/php/8.3/fpm/conf.d/20-xmlreader.ini, /etc/php/8.3/fpm/conf.d/20-xmlwriter.ini, /etc/php/8.3/fpm/conf.d/20-xsl.ini, /etc/php/8.3/fpm/conf.d/20-yac.ini, /etc/php/8.3/fpm/conf.d/20-yaml.ini, /etc/php/8.3/fpm/conf.d/20-zip.ini, /etc/php/8.3/fpm/conf.d/20-zmq.ini, /etc/php/8.3/fpm/conf.d/25-mailparse.ini, /etc/php/8.3/fpm/conf.d/25-memcached.ini, /etc/php/8.3/fpm/conf.d/25-swoole.ini, /etc/php/8.3/fpm/conf.d/30-ds.ini, /etc/php/8.3/fpm/conf.d/30-inotify.ini, /etc/php/8.3/fpm/conf.d/30-maxminddb.ini, /etc/php/8.3/fpm/conf.d/30-protobuf.ini, /etc/php/8.3/fpm/conf.d/30-zstd.ini `

**Comment by Ym0T** [comment]
Thank you very much, I have fixed it. I am uploading the new Docker images. That will take a moment.

**Comment by Kuroiras** [comment]
now works great!!! tanks you so much
