### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by joti-prime** [Ym0T/pterodactyl-nginx-egg#15]
:/home/container$ ; if [[ ! -z "${COMPOSER_MODULES}" ]]; then composer require ${COMPOSER_MODULES} --working-dir=/home/container/webroot; fi;
/entrypoint.sh: eval: line 13: syntax error near unexpected token `;'
/entrypoint.sh: eval: line 13: `; if [[ ! -z "${COMPOSER_MODULES}" ]]; then composer require ${COMPOSER_MODULES} --working-dir=/home/container/webroot; fi;'

**Comment by Ym0T** [comment]
> :/home/container$ ; if [[ ! -z "${COMPOSER_MODULES}" ]]; then composer require ${COMPOSER_MODULES} --working-dir=/home/container/webroot; fi;
> /entrypoint.sh: eval: line 13: syntax error near unexpected token `;'
> /entrypoint.sh: eval: line 13: `; if [[ ! -z "${COMPOSER_MODULES}" ]]; then composer require ${COMPOSER_MODULES} --working-dir=/home/container/webroot; fi;'

Hello, you've come to the wrong Web-Egg. We do not offer a composer. The composer module offers another one here on github.
