### ISSUE TITLE
Add libxml extension

### ISSUE THREAD

**Issue by scharez** [Ym0T/pterodactyl-nginx-egg#2]
It would be greate if you can add the libxml extension to php.

And other usefull extensions as here: https://github.com/Sigma-Production/ptero-eggs/blob/main/Dockerfile

Thank you :)

**Comment by Ym0T** [comment]
Hello scharez,

almost all extensions have already been added. I will add a few more from Sigma Production.
I will also add libxml.

These are the current extensions:
mysqlnd, opcache, pdo, psr, xml, bcmath, calendar, ctype, curl, dom, exif, ffi, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, mbstring, memcache, mongodb, msgpack, mysqli, odbc, pcov, pdo_dblib, pdo_firebird, pdo_mysql, pdo_odbc, pdo_pgsql, pdo_sqlite, pgsql, phar, posix, ps, pspell, readline, shmop, simplexml, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, mailparse, memcached, inotify, maxminddb, protobuf

**Comment by Ym0T** [comment]
Sorry, I made a mistake.
Libxml is already installed during the installation.

**Comment by scharez** [comment]
> Hello scharez,
> 
> almost all extensions have already been added. I will add a few more from Sigma Production. I will also add libxml.
> 
> These are the current extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, psr, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, memcache, mongodb, msgpack, mysqli, odbc, pcov, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, ps, pspell, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, mailparse, memcached, inotify, maxminddb, protobuf, Zend OPcache

Thank you very much.

Nice work!
