### ISSUE TITLE
Display logs of webserver in console?

### ISSUE THREAD

**Issue by scharez** [Ym0T/pterodactyl-nginx-egg#3]
Hi, 

Would it be possible to display the logs in the console? (access-log)?
And maybe enable and disable it, with a config property :)

**Comment by Ym0T** [comment]
Hello, I'll try to integrate the function tonight. 👍

**Comment by Ym0T** [comment]
The functionality has been added.
Load the new egg into your panel and update the nginx.conf (https://github.com/Ym0T/pterodactyl-nginx-egg/blob/main/nginx/nginx.conf)

**Comment by Ym0T** [comment]
Have you already tested the new function?

> Hi,
> 
> Would it be possible to display the logs in the console? (access-log)? And maybe enable and disable it, with a config property :)
