### ISSUE TITLE
Add php gd extension

### ISSUE THREAD

**Issue by scharez** [Ym0T/pterodactyl-nginx-egg#4]
Adding support for the php gd extenstion?

**Comment by scharez** [comment]
These are not the currently availabe extension?

https://github.com/Ym0T/pterodactyl-nginx-egg/issues/2#issuecomment-1908635676

**Comment by Ym0T** [comment]
The current ones are in the readme

**Comment by scharez** [comment]
Ah okay. GD will probably be the last extension I need ^^

Thank you!

**Comment by Ym0T** [comment]
No problem. Somehow a few changes removed that. Sorry

**Comment by Ym0T** [comment]
Which PHP version are you using?
Because it is installed in PHP8.3 and not in PHP7.3.

**Comment by Ym0T** [comment]
The extension is now available in all PHP versions.

**Comment by scharez** [comment]
Thank you very much. I only got 1 propblem that in the php folder, the session folder didn´t exist. So i had manualy create it. But now everything works. 

Maybe you could add the folder to git ^^

**Comment by Ym0T** [comment]
I already had this problem myself. But for some reason I didnt added it. 
I'll take care of it.
