### ISSUE TITLE
FEAT Request

### ISSUE THREAD

**Issue by scharez** [Ym0T/pterodactyl-nginx-egg#5]
Hi, I havent found some contact informations?

Can you maybe help me to create a custom pterodacty egg?

I want to use https://docs.directus.io/getting-started/quickstart.html it can be run via docker or using the cli (npm).

Could you tell me if this would be posible?

**Comment by Ym0T** [comment]
Hello Scharez,

please message me on: YmoT@tuta.com

Best regards
Tom
