### ISSUE TITLE
php-fpm.sock missing 

### ISSUE THREAD

**Issue by xLeviNx** [Ym0T/pterodactyl-nginx-egg#8]
After installing php version 8.2 and defining php version 8.2, it is missing the php-fpm.sock in tmp/

**Comment by Ym0T** [comment]
Hello,

you have to change the PHP version in the text file too in your directory. "php_version.txt"

Best regards
Tom

**Comment by xLeviNx** [comment]
Hi php version in the text file was also changed. This seems to be isolated to just the 8.2 version. All other versions the php-fpm.sock will be made

**Comment by Ym0T** [comment]
All right, please go through these instructions completely to see if you have forgotten any junk.

Step 1: File "php_version.txt" -> change content to "8.2".
![grafik](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/104158130/ba6a7585-a1c8-49b6-b177-40b06f785ed4)

Step 2: On the "Startup" page in your Pterodactyl panel, change "PHP VERSION" to "8.2".
![grafik](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/104158130/e61fb575-0bf8-4c08-b312-82f8cf9eabc4)

Step 3: Change Docker image to "...nginx_php:8.2"
![grafik](https://github.com/Ym0T/pterodactyl-nginx-egg/assets/104158130/e4840002-7cb9-49bb-be52-f3f361b156ef)

**Comment by Ym0T** [comment]
> After installing php version 8.2 and defining php version 8.2, it is missing the php-fpm.sock in tmp/

Did you use a different version before without any problems? If my last instructions didn't help?

**Comment by xLeviNx** [comment]
Followed those steps as well and it didn't install on version 8.2 again. I installed on 8.3 so its fine now but not sure why it failed on 8.2
