### ISSUE TITLE
Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by scharez** [Ym0T/pterodactyl-nginx-egg#9]
Hi,

I am getting the following error in the browser console, when I try to launch my Angular Application.

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

Is there something wrong with the nginx server itslef?

**Comment by Ym0T** [comment]
Hello, was the problem with you or what exactly was the solution?

**Comment by scharez** [comment]
I have not solved the problem yet. When i launch my angular via aa.name.domain.at it works. When i launch it via name.domain.at/app the error above gets thrown in the browser.

I made a stackoverflow entry for my problem.

https://stackoverflow.com/q/78835963/16052813

Maybe you can help me?
